name: main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            curl python3-dev python3-poetry python3-cachecontrol
          python3 -m poetry install

      - name: Build
        run: |
          python3 -m poetry run ./make.py import-at
          python3 -m poetry run ./make.py build ./dir

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./dir

  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: build
    concurrency: ci-${{ github.ref }}
    if: (github.event_name != 'pull_request' && github.ref == 'refs/heads/source')
    steps:
      - name: Download Results
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ./dir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dir
          publish_branch: main
